kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
spec:
  storageClassName: gp3-us-west-1a
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://us-west-1a/vol-......
    fsType: ext4
