kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins
spec:
  storageClassName: ebs-sc
  volumeName: "jenkins"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
