kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins
spec:
  storageClassName: gp3-us-west-1a
  volumeName: "jenkins"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
