---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-access
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-access-binding
subjects:
  - kind: ServiceAccount
    name: kuber-gha-rs-no-permission
    namespace: arc-systems
roleRef:
  kind: ClusterRole
  name: deployment-access
  apiGroup: rbac.authorization.k8s.io
