#docker buildx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildkit-deployment-manager
  namespace: buildkit
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

#kubectl auth can-i get deployments --as system:serviceaccount:arc-systems:kuber-gha-rs-no-permission -n buildkit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildkit-deployment-binding
  namespace: buildkit
subjects:
  - kind: ServiceAccount
    name: kuber-gha-rs-no-permission
    namespace: arc-systems
roleRef:
  kind: Role
  name: buildkit-deployment-manager
  apiGroup: rbac.authorization.k8s.io
---
#github controller runners

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: arc-systems
  name: create-roles-permission
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: arc-systems
  name: gha-runner-scale-set-rolebinding
subjects:
- kind: ServiceAccount
  name: gha-runner-scale-set-controller-gha-rs-controller
  namespace: arc-systems
roleRef:
  kind: Role
  name: create-roles-permission
  apiGroup: rbac.authorization.k8s.io
