# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: kuber
    steps:
      - uses: actions/checkout@v4

      - name: docker buildx create
        run: |
          docker buildx create \
                --name buildkitd-arm \
                --node buildkitd-arm \
                --driver kubernetes \
                --driver-opt replicas=3 \
                --driver-opt loadbalance=random \
                --driver-opt namespace=buildkit \
                --use && \
              # Build the Docker image using the Dockerfile
              docker buildx build --platform linux/arm64 -t my-image:latest -f Dockerfile . --load

      - name: buildx inspect
        run: |
          docker buildx inspect --bootstrap --builder buildkitd-arm
          docker buildx du
