name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: kuber
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        run: |
          docker buildx create \
            --name buildkitd-arm \
            --node buildkitd-arm \
            --driver kubernetes \
            --driver-opt replicas=3 \
            --driver-opt loadbalance=random \
            --driver-opt namespace=buildkit \
            --use

      - name: Build and Push with S3 Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Build the image using S3 cache
          docker buildx build \
            --platform linux/arm64 \
            -t my-image:latest \
            -f Dockerfile . \
            --load

      - name: Buildx Inspect
        run: |
          docker buildx inspect --bootstrap --builder buildkitd-arm
          docker buildx du
