name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: kuber
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        run: |
          docker buildx create \
            --name buildkitd-arm \
            --node buildkitd-arm \
            --driver kubernetes \
            --driver-opt replicas=2 \
            --driver-opt loadbalance=random \
            --driver-opt namespace=buildkit \
            --use

      - name: Build and Push with S3 Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Build the image using S3 cache
          docker buildx build \
            --platform linux/arm64 \
            --cache-from=type=s3,region=$AWS_REGION,bucket=buildkit-cache-minikube,mode=max \
            --cache-to=type=s3,region=$AWS_REGION,bucket=buildkit-cache-minikube,mode=max \
            -t serbenyuk/nextjs:latest \
            -f Dockerfile . \
            --load

      - name: Buildx Inspect
        run: |
          docker buildx inspect --bootstrap --builder buildkitd-arm
          docker buildx du

      # Optional: Push the Signed Image
      - name: Push Signed Image
        run: |
          docker push serbenyuk/nextjs:latest

      # Step: Install Cosign
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Decode cosign key and save it
        run: echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      # Step: Sign the Image with Cosign
      - name: Sign Docker Image with Cosign
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key --yes serbenyuk/nextjs:latest

      # Step: Verify the Image Signature with Cosign
      - name: Verify Docker Image Signature with Cosign
        run: |
          cosign verify --key --yes ${{ secrets.COSIGN_PASSWORD }} serbenyuk/nextjs:latest
