name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: kuber

    # Define a matrix for multiple configurations
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [linux/amd64, linux/arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Buildx builder
        run: |
          docker buildx create \
            --name buildkitd-${{ matrix.architecture }} \
            --node buildkitd-${{ matrix.architecture }} \
            --driver kubernetes \
            --driver-opt replicas=2 \
            --driver-opt loadbalance=random \
            --driver-opt namespace=buildkit \
            --use

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform ${{ matrix.architecture }} \
            -t my-image:${{ matrix.architecture }} \
            -f Dockerfile . \
            --load

      - name: Inspect Buildx Builder
        run: docker buildx inspect --bootstrap --builder buildkitd-${{ matrix.architecture }}

      - name: Display Disk Usage
        run: docker buildx du
